// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: timetaskcache.proto

package org.sunshine.lc.test.proto;

public final class TimeTaskCacheProto {
  private TimeTaskCacheProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TimeTaskCacheOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TimeTaskCache)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
     */
    int getCacheCount();
    /**
     * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
     */
    boolean containsCache(
        String key);
    /**
     * Use {@link #getCacheMap()} instead.
     */
    @Deprecated
    java.util.Map<String, TimeTask>
    getCache();
    /**
     * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
     */
    java.util.Map<String, TimeTask>
    getCacheMap();
    /**
     * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
     */

    TimeTask getCacheOrDefault(
        String key,
        TimeTask defaultValue);
    /**
     * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
     */

    TimeTask getCacheOrThrow(
        String key);
  }
  /**
   * Protobuf type {@code TimeTaskCache}
   */
  public static final class TimeTaskCache extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TimeTaskCache)
      TimeTaskCacheOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TimeTaskCache.newBuilder() to construct.
    private TimeTaskCache(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TimeTaskCache() {
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TimeTaskCache();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TimeTaskCache(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                cache_ = com.google.protobuf.MapField.newMapField(
                    CacheDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000001;
              }
              com.google.protobuf.MapEntry<String, TimeTask>
              cache__ = input.readMessage(
                  CacheDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              cache_.getMutableMap().put(
                  cache__.getKey(), cache__.getValue());
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TimeTaskCacheProto.internal_static_TimeTaskCache_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    @Override
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 1:
          return internalGetCache();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TimeTaskCacheProto.internal_static_TimeTaskCache_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TimeTaskCache.class, Builder.class);
    }

    public static final int CACHE_FIELD_NUMBER = 1;
    private static final class CacheDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          String, TimeTask> defaultEntry =
              com.google.protobuf.MapEntry
              .<String, TimeTask>newDefaultInstance(
                  TimeTaskCacheProto.internal_static_TimeTaskCache_CacheEntry_descriptor,
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.MESSAGE,
                  TimeTask.getDefaultInstance());
    }
    private com.google.protobuf.MapField<
        String, TimeTask> cache_;
    private com.google.protobuf.MapField<String, TimeTask>
    internalGetCache() {
      if (cache_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            CacheDefaultEntryHolder.defaultEntry);
      }
      return cache_;
    }

    public int getCacheCount() {
      return internalGetCache().getMap().size();
    }
    /**
     * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
     */

    @Override
    public boolean containsCache(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      return internalGetCache().getMap().containsKey(key);
    }
    /**
     * Use {@link #getCacheMap()} instead.
     */
    @Override
    @Deprecated
    public java.util.Map<String, TimeTask> getCache() {
      return getCacheMap();
    }
    /**
     * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
     */
    @Override

    public java.util.Map<String, TimeTask> getCacheMap() {
      return internalGetCache().getMap();
    }
    /**
     * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
     */
    @Override

    public TimeTask getCacheOrDefault(
        String key,
        TimeTask defaultValue) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, TimeTask> map =
          internalGetCache().getMap();
      return map.containsKey(key) ? map.get(key) : defaultValue;
    }
    /**
     * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
     */
    @Override

    public TimeTask getCacheOrThrow(
        String key) {
      if (key == null) { throw new NullPointerException(); }
      java.util.Map<String, TimeTask> map =
          internalGetCache().getMap();
      if (!map.containsKey(key)) {
        throw new IllegalArgumentException();
      }
      return map.get(key);
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      com.google.protobuf.GeneratedMessageV3
        .serializeStringMapTo(
          output,
          internalGetCache(),
          CacheDefaultEntryHolder.defaultEntry,
          1);
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (java.util.Map.Entry<String, TimeTask> entry
           : internalGetCache().getMap().entrySet()) {
        com.google.protobuf.MapEntry<String, TimeTask>
        cache__ = CacheDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(1, cache__);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TimeTaskCache)) {
        return super.equals(obj);
      }
      TimeTaskCache other = (TimeTaskCache) obj;

      if (!internalGetCache().equals(
          other.internalGetCache())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (!internalGetCache().getMap().isEmpty()) {
        hash = (37 * hash) + CACHE_FIELD_NUMBER;
        hash = (53 * hash) + internalGetCache().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TimeTaskCache parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimeTaskCache parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimeTaskCache parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimeTaskCache parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimeTaskCache parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimeTaskCache parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimeTaskCache parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TimeTaskCache parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TimeTaskCache parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TimeTaskCache parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TimeTaskCache parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TimeTaskCache parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TimeTaskCache prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TimeTaskCache}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TimeTaskCache)
        TimeTaskCacheOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TimeTaskCacheProto.internal_static_TimeTaskCache_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetCache();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 1:
            return internalGetMutableCache();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TimeTaskCacheProto.internal_static_TimeTaskCache_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TimeTaskCache.class, Builder.class);
      }

      // Construct using com.authine.h3yun.engine.controller.test.proto.TimeTaskCacheProto.TimeTaskCache.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        internalGetMutableCache().clear();
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TimeTaskCacheProto.internal_static_TimeTaskCache_descriptor;
      }

      @Override
      public TimeTaskCache getDefaultInstanceForType() {
        return TimeTaskCache.getDefaultInstance();
      }

      @Override
      public TimeTaskCache build() {
        TimeTaskCache result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TimeTaskCache buildPartial() {
        TimeTaskCache result = new TimeTaskCache(this);
        int from_bitField0_ = bitField0_;
        result.cache_ = internalGetCache();
        result.cache_.makeImmutable();
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TimeTaskCache) {
          return mergeFrom((TimeTaskCache)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TimeTaskCache other) {
        if (other == TimeTaskCache.getDefaultInstance()) return this;
        internalGetMutableCache().mergeFrom(
            other.internalGetCache());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TimeTaskCache parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TimeTaskCache) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.MapField<
          String, TimeTask> cache_;
      private com.google.protobuf.MapField<String, TimeTask>
      internalGetCache() {
        if (cache_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              CacheDefaultEntryHolder.defaultEntry);
        }
        return cache_;
      }
      private com.google.protobuf.MapField<String, TimeTask>
      internalGetMutableCache() {
        onChanged();;
        if (cache_ == null) {
          cache_ = com.google.protobuf.MapField.newMapField(
              CacheDefaultEntryHolder.defaultEntry);
        }
        if (!cache_.isMutable()) {
          cache_ = cache_.copy();
        }
        return cache_;
      }

      public int getCacheCount() {
        return internalGetCache().getMap().size();
      }
      /**
       * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
       */

      @Override
      public boolean containsCache(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        return internalGetCache().getMap().containsKey(key);
      }
      /**
       * Use {@link #getCacheMap()} instead.
       */
      @Override
      @Deprecated
      public java.util.Map<String, TimeTask> getCache() {
        return getCacheMap();
      }
      /**
       * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
       */
      @Override

      public java.util.Map<String, TimeTask> getCacheMap() {
        return internalGetCache().getMap();
      }
      /**
       * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
       */
      @Override

      public TimeTask getCacheOrDefault(
          String key,
          TimeTask defaultValue) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, TimeTask> map =
            internalGetCache().getMap();
        return map.containsKey(key) ? map.get(key) : defaultValue;
      }
      /**
       * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
       */
      @Override

      public TimeTask getCacheOrThrow(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        java.util.Map<String, TimeTask> map =
            internalGetCache().getMap();
        if (!map.containsKey(key)) {
          throw new IllegalArgumentException();
        }
        return map.get(key);
      }

      public Builder clearCache() {
        internalGetMutableCache().getMutableMap()
            .clear();
        return this;
      }
      /**
       * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
       */

      public Builder removeCache(
          String key) {
        if (key == null) { throw new NullPointerException(); }
        internalGetMutableCache().getMutableMap()
            .remove(key);
        return this;
      }
      /**
       * Use alternate mutation accessors instead.
       */
      @Deprecated
      public java.util.Map<String, TimeTask>
      getMutableCache() {
        return internalGetMutableCache().getMutableMap();
      }
      /**
       * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
       */
      public Builder putCache(
          String key,
          TimeTask value) {
        if (key == null) { throw new NullPointerException(); }
        if (value == null) { throw new NullPointerException(); }
        internalGetMutableCache().getMutableMap()
            .put(key, value);
        return this;
      }
      /**
       * <code>map&lt;string, .TimeTask&gt; cache = 1;</code>
       */

      public Builder putAllCache(
          java.util.Map<String, TimeTask> values) {
        internalGetMutableCache().getMutableMap()
            .putAll(values);
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TimeTaskCache)
    }

    // @@protoc_insertion_point(class_scope:TimeTaskCache)
    private static final TimeTaskCache DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TimeTaskCache();
    }

    public static TimeTaskCache getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimeTaskCache>
        PARSER = new com.google.protobuf.AbstractParser<TimeTaskCache>() {
      @Override
      public TimeTaskCache parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TimeTaskCache(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TimeTaskCache> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TimeTaskCache> getParserForType() {
      return PARSER;
    }

    @Override
    public TimeTaskCache getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface TimeTaskOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TimeTask)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string taskId = 1;</code>
     * @return The taskId.
     */
    String getTaskId();
    /**
     * <code>string taskId = 1;</code>
     * @return The bytes for taskId.
     */
    com.google.protobuf.ByteString
        getTaskIdBytes();

    /**
     * <code>int64 startTime = 2;</code>
     * @return The startTime.
     */
    long getStartTime();

    /**
     * <code>int64 endTime = 3;</code>
     * @return The endTime.
     */
    long getEndTime();
  }
  /**
   * Protobuf type {@code TimeTask}
   */
  public static final class TimeTask extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TimeTask)
      TimeTaskOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TimeTask.newBuilder() to construct.
    private TimeTask(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TimeTask() {
      taskId_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new TimeTask();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TimeTask(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              taskId_ = s;
              break;
            }
            case 16: {

              startTime_ = input.readInt64();
              break;
            }
            case 24: {

              endTime_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return TimeTaskCacheProto.internal_static_TimeTask_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return TimeTaskCacheProto.internal_static_TimeTask_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              TimeTask.class, Builder.class);
    }

    public static final int TASKID_FIELD_NUMBER = 1;
    private volatile Object taskId_;
    /**
     * <code>string taskId = 1;</code>
     * @return The taskId.
     */
    @Override
    public String getTaskId() {
      Object ref = taskId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        taskId_ = s;
        return s;
      }
    }
    /**
     * <code>string taskId = 1;</code>
     * @return The bytes for taskId.
     */
    @Override
    public com.google.protobuf.ByteString
        getTaskIdBytes() {
      Object ref = taskId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        taskId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STARTTIME_FIELD_NUMBER = 2;
    private long startTime_;
    /**
     * <code>int64 startTime = 2;</code>
     * @return The startTime.
     */
    @Override
    public long getStartTime() {
      return startTime_;
    }

    public static final int ENDTIME_FIELD_NUMBER = 3;
    private long endTime_;
    /**
     * <code>int64 endTime = 3;</code>
     * @return The endTime.
     */
    @Override
    public long getEndTime() {
      return endTime_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTaskIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, taskId_);
      }
      if (startTime_ != 0L) {
        output.writeInt64(2, startTime_);
      }
      if (endTime_ != 0L) {
        output.writeInt64(3, endTime_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTaskIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, taskId_);
      }
      if (startTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, startTime_);
      }
      if (endTime_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, endTime_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof TimeTask)) {
        return super.equals(obj);
      }
      TimeTask other = (TimeTask) obj;

      if (!getTaskId()
          .equals(other.getTaskId())) return false;
      if (getStartTime()
          != other.getStartTime()) return false;
      if (getEndTime()
          != other.getEndTime()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TASKID_FIELD_NUMBER;
      hash = (53 * hash) + getTaskId().hashCode();
      hash = (37 * hash) + STARTTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStartTime());
      hash = (37 * hash) + ENDTIME_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEndTime());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static TimeTask parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimeTask parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimeTask parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimeTask parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimeTask parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static TimeTask parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static TimeTask parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TimeTask parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static TimeTask parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static TimeTask parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static TimeTask parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static TimeTask parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(TimeTask prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TimeTask}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TimeTask)
        TimeTaskOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return TimeTaskCacheProto.internal_static_TimeTask_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return TimeTaskCacheProto.internal_static_TimeTask_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                TimeTask.class, Builder.class);
      }

      // Construct using com.authine.h3yun.engine.controller.test.proto.TimeTaskCacheProto.TimeTask.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        taskId_ = "";

        startTime_ = 0L;

        endTime_ = 0L;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return TimeTaskCacheProto.internal_static_TimeTask_descriptor;
      }

      @Override
      public TimeTask getDefaultInstanceForType() {
        return TimeTask.getDefaultInstance();
      }

      @Override
      public TimeTask build() {
        TimeTask result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public TimeTask buildPartial() {
        TimeTask result = new TimeTask(this);
        result.taskId_ = taskId_;
        result.startTime_ = startTime_;
        result.endTime_ = endTime_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof TimeTask) {
          return mergeFrom((TimeTask)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(TimeTask other) {
        if (other == TimeTask.getDefaultInstance()) return this;
        if (!other.getTaskId().isEmpty()) {
          taskId_ = other.taskId_;
          onChanged();
        }
        if (other.getStartTime() != 0L) {
          setStartTime(other.getStartTime());
        }
        if (other.getEndTime() != 0L) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        TimeTask parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (TimeTask) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object taskId_ = "";
      /**
       * <code>string taskId = 1;</code>
       * @return The taskId.
       */
      public String getTaskId() {
        Object ref = taskId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          taskId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string taskId = 1;</code>
       * @return The bytes for taskId.
       */
      public com.google.protobuf.ByteString
          getTaskIdBytes() {
        Object ref = taskId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          taskId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string taskId = 1;</code>
       * @param value The taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        taskId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string taskId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTaskId() {
        
        taskId_ = getDefaultInstance().getTaskId();
        onChanged();
        return this;
      }
      /**
       * <code>string taskId = 1;</code>
       * @param value The bytes for taskId to set.
       * @return This builder for chaining.
       */
      public Builder setTaskIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        taskId_ = value;
        onChanged();
        return this;
      }

      private long startTime_ ;
      /**
       * <code>int64 startTime = 2;</code>
       * @return The startTime.
       */
      @Override
      public long getStartTime() {
        return startTime_;
      }
      /**
       * <code>int64 startTime = 2;</code>
       * @param value The startTime to set.
       * @return This builder for chaining.
       */
      public Builder setStartTime(long value) {
        
        startTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 startTime = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartTime() {
        
        startTime_ = 0L;
        onChanged();
        return this;
      }

      private long endTime_ ;
      /**
       * <code>int64 endTime = 3;</code>
       * @return The endTime.
       */
      @Override
      public long getEndTime() {
        return endTime_;
      }
      /**
       * <code>int64 endTime = 3;</code>
       * @param value The endTime to set.
       * @return This builder for chaining.
       */
      public Builder setEndTime(long value) {
        
        endTime_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 endTime = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndTime() {
        
        endTime_ = 0L;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TimeTask)
    }

    // @@protoc_insertion_point(class_scope:TimeTask)
    private static final TimeTask DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new TimeTask();
    }

    public static TimeTask getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TimeTask>
        PARSER = new com.google.protobuf.AbstractParser<TimeTask>() {
      @Override
      public TimeTask parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TimeTask(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TimeTask> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<TimeTask> getParserForType() {
      return PARSER;
    }

    @Override
    public TimeTask getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TimeTaskCache_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TimeTaskCache_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TimeTaskCache_CacheEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TimeTaskCache_CacheEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TimeTask_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TimeTask_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\023timetaskcache.proto\"r\n\rTimeTaskCache\022(" +
      "\n\005cache\030\001 \003(\0132\031.TimeTaskCache.CacheEntry" +
      "\0327\n\nCacheEntry\022\013\n\003key\030\001 \001(\t\022\030\n\005value\030\002 \001" +
      "(\0132\t.TimeTask:\0028\001\">\n\010TimeTask\022\016\n\006taskId\030" +
      "\001 \001(\t\022\021\n\tstartTime\030\002 \001(\003\022\017\n\007endTime\030\003 \001(" +
      "\003BD\n.com.authine.h3yun.engine.controller" +
      ".test.protoB\022TimeTaskCacheProtob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_TimeTaskCache_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TimeTaskCache_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TimeTaskCache_descriptor,
        new String[] { "Cache", });
    internal_static_TimeTaskCache_CacheEntry_descriptor =
      internal_static_TimeTaskCache_descriptor.getNestedTypes().get(0);
    internal_static_TimeTaskCache_CacheEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TimeTaskCache_CacheEntry_descriptor,
        new String[] { "Key", "Value", });
    internal_static_TimeTask_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_TimeTask_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TimeTask_descriptor,
        new String[] { "TaskId", "StartTime", "EndTime", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
